package com.hcl.xpathApi;
public enum ENGINEERING_API {
	
	//Routing
	XPATH_FOR_CREATE_ROUTING_NAME,
	XPATH_FOR_CREATE_ROUTING_IDENTIFIER,
	XPATH_FOR_CREATE_ROUTING_VERSION,
	XPATH_FOR_CREATE_ROUTING_DESC,
	XPATH_FOR_CREATE_ROUTING_BUTTON,
	XPATH_FOR_CHANGE_ROUTING_BUTTON,
	XPATH_FOR_DELETE_ROUTING_BUTTON,
	XPATH_FOR_QUICKCHANGE_ROUTING_BUTTON,
	XPATH_FOR_CHANGE_ROUTING_SITE_NAME,
	XPATH_FOR_CHANGE_ROUTING_IDENTIFIER,
	XPATH_FOR_CHANGE_ROUTING_VERSION,
	XPATH_FOR_CHANGE_ROUTING_DESC,
	XPATH_FOR_DELETE_ROUTING_SITENAME,
	XPATH_FOR_DELETE_ROUTING_IDENTIFIER,
	XPATH_FOR_DELETE_ROUTING_VERSION,
	XPATH_FOR_QUICKCHANGE_ROUTING_NAME,
	XPATH_FOR_QUICKCHANGE_ROUTING_IDENTIFIER,
	XPATH_FOR_QUICKCHANGE_ROUTING_VERSION,
	XPATH_FOR_QUICKCHANGE_ROUTING_DESC,
	
	
	//Enterprise Item
	XPATH_FOR_CREATE_ITEM_DESC,
	XPATH_FOR_CREATE_ITEM_NAME,
	XPATH_FOR_CREATE_ITEM_BUTTON_CLICK,
	
	// ITEMRevisionObject
	XPATH_FOR_CREATEITEM_REVISION_SITENAME,
	XPATH_FOR_CREATEITEM_REVISION_ITEMNAME,
	XPATH_FOR_CREATEITEM_REVISION_ITEMREVISIONNAME,
	XPATH_FOR_CREATEITEM_REVISION_ITEMDESC,
	XPATH_FOR_CREATEITEM_REVISION_BUTTON

	
	//vihs
	
	}
